export const USER_NAME = 'USER_NAME';
export const USER_FULLNAME = 'USER_FULLNAME';
export const SET_AUTH_EMAIL = "SET_AUTH_EMAIL";
export const SET_AUTH_PASSWORD = "SET_AUTH_PASSWORD";
export const SET_AUTH_MODAL = "SET_AUTH_MODAL";
export const SET_LOGIN_DATA = "SET_LOGIN_DATA";
export const SET_UPDATED_DATA = "SET_UPDATED_DATA";
// work bag satus

export const SET_ERROR_WORKBAG = "SET_ERROR";
export const LOGOUT = "LOGOUT";
//workbags 
export const SET_ALL_WORK_BAG = "SET_ALL_WORK_BAG";
export const SET_WORK_BAG_DETAIL = "SET_WORK_BAG_DETAIL";
export const SET_WORK_BAG_DETAIL_ID = "SET_WORK_BAG_DETAIL_ID";
export const SET_WORKBAG_TOTAL_PAGE = "SET_WORKBAG_TOTAL_PAGE";
export const SET_WORKBAG_CURRENT_PAGE = "SET_WORKBAG_CURRENT_PAGE";

//notifications
export const SET_ALL_NOTIFICATIONS = "SET_ALL_NOTIFICATIONS";
export const SET_NOTIFICATIONS_TOTAL_PAGE = "SET_NOTIFICATIONS_TOTAL_PAGE";
export const SET_NOTIFICATIONS_CURRENT_PAGE = "SET_NOTIFICATIONS_CURRENT_PAGE";
// setAll
export const SET_ALL_USD_NEWS = "SET_ALL_USD_NEWS";
export const SET_ALL_JMD_NEWS = "SET_ALL_JMD_NEWS";
export const SET_NEWS_LIMIT = "SET_NEWS_LIMIT";
export const SET_ALL_ALERTS = "SET_ALL_ALERTS";
// simulaiton
export const SET_DEFAULT_SIMULATION_SETTING_USD = "SET_DEFAULT_SIMULATION_SETTING_USD";
export const SET_DEFAULT_SIMULATION_SETTING_JMD = "SET_DEFAULT_SIMULATION_SETTING_JMD";
export const SET_BROKER_USD = "SET_BROKER_USD";
export const SET_BROKER_JMD = "SET_BROKER_JMD";
export const SET_ORDER_LANGUAGE = "SET_ORDER_LANGUAGE";
export const SET_COMPANY_ARR = "SET_COMPANY_ARR";
export const SET_ORDER_ID = "SET_ORDER_ID";
export const SET_ORDER_LIST_USD = "SET_ORDER_LIST_USD";
export const SET_ORDER_LIST_JMD = "SET_ORDER_LIST_JMD";


// notification
//SET_ALL_USD_notification
export const SET_ALL_USD_notification = "SET_ALL_USD_notification";
export const SET_ALL_JMD_notification = "SET_ALL_JMD_notification";
export const SET_notification_LIMIT = "SET_notification_LIMIT";
//game
export const SET_ALL_GAMES = "SET_ALL_GAMES";
export const SET_MY_GAME = "SET_MY_GAME";
export const SET_GAME_DETAIL = "SET_GAME_DETAIL";
//gameDetail

//search
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";
export const SET_TRENDING_DEFAULT = "SET_TRENDING_DEFAULT";
export const SET_TRENDING_DEFAULT_JMD = "SET_TRENDING_DEFAULT_JMD";
export const SET_USD_NEWS_SEARCH = "SET_USD_NEWS_SEARCH";
export const SET_JMD_NEWS_SEARCH = "SET_JMD_NEWS_SEARCH";
export const SET_JMD_SYMBOL_SEARCH = "SET_JMD_SYMBOL_SEARCH";
export const SET_USD_SYMBOL_SEARCH = "SET_USD_SYMBOL_SEARCH";
export const SET_USD_STOCK_SEARCH = "SET_USD_STOCK_SEARCH";
export const SET_JMD_STOCK_SEARCH = "SET_JMD_STOCK_SEARCH";
export const SET_SEARCH_ANALYSIS = "SET_SEARCH_ANALYSIS";
export const SET_SECTOR_INFORMATION = "SET_SECTOR_INFORMATION";
export const SET_SECTOR_INFORMATION_JMD = "SET_SECTOR_INFORMATION_JMD";

export const SET_SECTOR_INFORMATION_COMPARE = "SET_SECTOR_INFORMATION_COMPARE";
export const SET_ALL_INVESTMENT = "SET_ALL_INVESTMENT";
export const SET_ONE_BROKER = "SET_ONE_BROKER";
//watchlist
export const SET_WATCHLIST_STOCK = "SET_WATCHLIST_STOCK";
export const SET_WATCHLIST_FOREX = "SET_WATCHLIST_FOREX";
export const SET_WATCHLIST_BOND = "SET_WATCHLIST_BOND";

//getTrending 





